# Generated by Django 3.2.9 on 2022-09-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cronica',
            options={'ordering': ['-publish'], 'verbose_name_plural': 'cronicas'},
        ),
    ]
