# Generated by Django 3.2.9 on 2022-09-12 16:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('file_pdf', models.FileField(upload_to='pdf/%Y/%m/%d/', verbose_name='bases')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenido')),
                ('image', models.ImageField(blank=True, upload_to='torneos', verbose_name='imagen')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('finish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='final')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('location', models.CharField(max_length=200, verbose_name='localidad')),
                ('province', models.CharField(max_length=200, verbose_name='provincia')),
                ('registre', models.TextField(blank=True, verbose_name='registrarse')),
                ('inscribed', models.URLField(blank=True, verbose_name='inscritos')),
            ],
            options={
                'verbose_name_plural': 'torneos',
                'ordering': ['-start'],
            },
        ),
    ]
