# Generated by Django 3.2.9 on 2022-09-12 16:47

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='registre',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='registrarse'),
        ),
    ]
