# Generated by Django 3.2.9 on 2022-09-15 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_torneo_registre'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='end_registration',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='fin de inscripción'),
        ),
    ]
