# Generated by Django 3.2.9 on 2022-09-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_torneo_end_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
