# Generated by Django 3.2.9 on 2022-09-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneo_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='aforo'),
        ),
    ]
