# Generated by Django 3.2.9 on 2022-09-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tournamentregistration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'ordering': ['-surnames'], 'verbose_name_plural': 'registros'},
        ),
    ]
