# Generated by Django 3.2.9 on 2022-09-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220922_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.torneo', verbose_name='torneo'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together={('name', 'surnames', 'mail', 'tournament')},
        ),
    ]
