# Generated by Django 3.2.9 on 2022-09-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20220922_0858'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentregistration',
            unique_together=set(),
        ),
    ]
