# Generated by Django 3.2.9 on 2022-09-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tournamentregistration_unique_together'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('name', 'surnames', 'mail'), name='unique_tournamentregistration'),
        ),
    ]
