# Generated by Django 3.2.9 on 2022-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tournamentregistration_unique_tournamentregistration'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_tournamentregistration',
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('tournament', 'name', 'surnames', 'mail'), name='unique_tournamentregistration'),
        ),
    ]
