# Generated by Django 3.2.9 on 2022-09-22 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220922_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
