# Generated by Django 3.2.9 on 2022-09-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20220922_1218'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_tournamentregistration',
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='tournament_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='nombre del torneo'),
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('name', 'surnames', 'mail'), name='unique_tournamentregistration'),
        ),
    ]
