# Generated by Django 3.2.9 on 2022-09-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220922_1633'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tournamentregistration',
            name='unique_tournamentregistration',
        ),
        migrations.AddConstraint(
            model_name='tournamentregistration',
            constraint=models.UniqueConstraint(fields=('name', 'surnames', 'mail', 'tournament_title'), name='unique_tournamentregistration'),
        ),
    ]
