# Generated by Django 3.2.9 on 2022-09-22 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20220922_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TournamentRegistration',
        ),
    ]
